[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.mongodb", "php82Extensions.redis"]

[phases.install]
cmds = ["composer install --no-interaction --optimize-autoloader --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."